export { default as Payments} from "./Payments"
export { default as PersonalInfo} from "./PersonalInfo"
export { default as Setting} from "./Setting"
export { default as Wishlist} from "./Wishlist"
export { default as Profile} from "./Profile"
